// @ts-check

const topCategory = ({ label, section, items }) => ({
  type: 'category',
  label,
  link: {
    type: 'doc',
    id: `${section}/README`,
  },
  className: `sidebar-section-top sidebar-section-${section}`,
  collapsed: true,
  items,
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    { type: 'doc', id: 'README', className: 'sidebar-docs-index-hidden' },
    topCategory({
      label: '核心板',
      section: 'core-board',
      items: [{ type: 'autogenerated', dirName: 'core-board' }],
    }),
    topCategory({
      label: '主板',
      section: 'main-board',
      items: [{ type: 'autogenerated', dirName: 'main-board' }],
    }),
    topCategory({
      label: '终端',
      section: 'terminal',
      items: [{ type: 'autogenerated', dirName: 'terminal' }],
    }),
    topCategory({
      label: 'AIOT解决方案',
      section: 'aiot-solutions',
      items: [{ type: 'autogenerated', dirName: 'aiot-solutions' }],
    }),
    topCategory({
      label: 'OpenHarmony',
      section: 'openharmony',
      items: [{ type: 'autogenerated', dirName: 'openharmony' }],
    }),
    topCategory({
      label: 'MineHarmony',
      section: 'mineharmony',
      items: [{ type: 'autogenerated', dirName: 'mineharmony' }],
    }),
    topCategory({
      label: '其他',
      section: 'reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    }),
  ],
};

module.exports = sidebars;
